version: "2.2"
x-common_variables: &common_variables
  # ++   env_file: environment-of-cubist

services:
  openai:
    depends_on:
      clickhouse:
        condition: service_healthy
    image: openai
    hostname: openai
    container_name: openai
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USERNAME: lupi
      CLICKHOUSE_PASSWORD: lupi
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DATABASE: openai
    ports:
      - 5000:5000
    working_dir: /app
    stdin_open: true
    tty: true
    #command: bash
    volumes:
      - .:/app/

  clickhouse:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    environment:
      CLICKHOUSE_DB: openai
      CLICKHOUSE_USER: lupi
      CLICKHOUSE_PASSWORD: lupi
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile: 262144

volumes:
  clickhouse-data:
